apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: llj4m8qbl-go 
  janus-idp.io/tekton: llj4m8qbl-go
  backstage.io/kubernetes-id: llj4m8qbl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: llj4m8qbl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  