apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: llj4m8qbl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: llj4m8qbl-go 
  name: llj4m8qbl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: llj4m8qbl-go 
